# A Simple Network from Scratch: Julia Edition

Following a [post from Andrew Trask](https://iamtrask.github.io/2015/07/12/basic-python-network/) showing how to design a network from scratch in python, just using numpy, I figured it would be a useful learning exercise to do the same with Julia. While Julia already has a couple of powerful frameworks for Machine Learning, this is to cement an intuitive understanding of the underlying working of a neural network as well develop an understanding of the core functionalities of Julia.  

### Creating Arrays

In [1]:
using LinearAlgebra

X = [[0 1 1]; [0 1 1];[1 0 1]; [1 1 1]]
y = transpose([0 0 1 1])
println(size(X))
println(size(y))

(4, 3)
(4, 1)


In [2]:
X

4×3 Array{Int32,2}:
 0  1  1
 0  1  1
 1  0  1
 1  1  1

In [3]:
y

4×1 Transpose{Int32,Array{Int32,2}}:
 0
 0
 1
 1

As you can see frm the print out, we now have our arrays in the correct format.

### Defining Functions

In the cell below, I'll define a sigmoid function. 

In [28]:
#function sigmoid(x,deriv = false)
#    if deriv == true
#        return x*(1-x)
#    end
#    return 1.0 /(1.0+exp(-x))
#end

function sigmoid(z)
    return 1.0 ./(1.0 .+ exp(.-z))
end

function deriv(z)
    return z .*(1 .- z)
end

deriv (generic function with 1 method)

For practise, let's print calculate the value of sigmoid for -1 to 1 and intervals of 0.1 and plot them. 

In [5]:
val_range = -10:0.5:10
full_range = collect(val_range)
sigmoid_array = zeros(length(full_range))
for (index,x) in enumerate(full_range)
    sigmoid_array[index] = sigmoid(x)
end

In [6]:
sigmoid_array

41-element Array{Float64,1}:
 4.5397868702434395e-5 
 7.484622751061124e-5  
 0.00012339457598623172
 0.00020342697805520653
 0.0003353501304664781 
 0.0005527786369235996 
 0.0009110511944006454 
 0.0015011822567369917 
 0.0024726231566347743 
 0.004070137715896128  
 0.0066928509242848554 
 0.01098694263059318   
 0.01798620996209156   
 ⋮                     
 0.9890130573694068    
 0.9933071490757153    
 0.995929862284104     
 0.9975273768433653    
 0.998498817743263     
 0.9990889488055994    
 0.9994472213630764    
 0.9996646498695336    
 0.9997965730219448    
 0.9998766054240137    
 0.9999251537724895    
 0.9999546021312976    

And below we'll just make a simple plot to check we're getting what we'd expect from our sigmoid function. 

In [7]:
using Plots
plotly()
plot(full_range, sigmoid_array)

<!DOCTYPE html>
 
 
 Plots.jl

### Random Number Generation

Now we need to randomly initialise some random numbers

In [63]:
#syn0 = randn(Float64, (3,4))
syn1 = randn(Float64, (3,1))
transpose(syn1)
syn1

3×1 Array{Float64,2}:
 -1.2175140033466896 
  0.6639190654576367 
  0.18607079419065026

In [9]:
using Statistics
println(mean(syn1))
#println(mean(syn1))

0.0377748916420669


In [64]:
print(size(X))
X

(4, 3)

4×3 Array{Int32,2}:
 0  1  1
 0  1  1
 1  0  1
 1  1  1

In [65]:
example = X*syn1

4×1 Array{Float64,2}:
  0.8499898596482869 
  0.8499898596482869 
 -1.0314432091560393 
 -0.36752414369840264

In [66]:
sigmoid(example[1])

0.7005650152994582

In [67]:
sigmoid.(X*syn1)

4×1 Array{Float64,2}:
 0.7005650152994582 
 0.7005650152994582 
 0.26280440365231117
 0.4091394109298443 

In [68]:
deriv(sigmoid.(X*syn1))

4×1 Array{Float64,2}:
 0.20977367463792806
 0.20977367463792806
 0.19373824907326426
 0.2417443533538243 

In [74]:
for j in 1:1:100
    global l1
    l0 = X #l0 = (4,3)
    l1 = sigmoid.(X*syn1) #l1 = 4,1
    #println(l1)
    l1_error = y - l1 #l1_error = 4,
    #println(l1_error)
    l1_delta = l1_error .* deriv.(l1)
    #print(size(l1_delta))
    syn1 += transpose(l0) * l1_delta
end
print(l1)

[0.0344936; 0.0344936; 0.995205; 0.956299]